name: "Prerelease Cleanup Action"
description: "Remove old prereleases while maintaining actual releases"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  delete-tags:
    description: "Delete release tags"
    required: false
    default: true
  dry-run:
    description: "Only output releases that would be deleted"
    required: false
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
