#!/bin/sh

set -e

PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin

download_wp() {
	BASE_DIR="/usr/src/wordpress"
	VERSION="$1"
	if [ "${VERSION}" = "nightly" ] || [ "${VERSION}" = "trunk" ]; then
		TESTS_TAG="trunk"
	elif [ "${VERSION}" = "latest" ]; then
		VERSIONS=$(curl -s https://api.wordpress.org/core/version-check/1.7/)
		LATEST=$(echo "${VERSIONS}" | jq -r '.offers | map(select( .response == "upgrade")) | .[0].version')
		if [ -z "${LATEST}" ]; then
			echo "Unable to detect the latest WP version"
			exit 1
		fi

		download_wp "${LATEST}"
		ln -sf "${BASE_DIR}/wordpress-${LATEST}"           "${BASE_DIR}/wordpress-latest"
		ln -sf "${BASE_DIR}/wordpress-tests-lib-${LATEST}" "${BASE_DIR}/wordpress-tests-lib-latest"
		return
	elif [ "${VERSION%.x}" != "${VERSION}" ]; then
		VER="${VERSION}"
		LATEST=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq --arg version "${VERSION%.x}" -r '.offers | map(select(.version | startswith($version))) | sort_by(.version) | reverse | .[0].version')
		download_wp "${LATEST}"
		ln -sf "${BASE_DIR}/wordpress-${LATEST}"           "${BASE_DIR}/wordpress-${VER}"
		ln -sf "${BASE_DIR}/wordpress-tests-lib-${LATEST}" "${BASE_DIR}/wordpress-tests-lib-${VER}"
		return
	else
		TESTS_TAG="tags/${VERSION}"
	fi

	if [ ! -d "${BASE_DIR}/wordpress-${VERSION}" ]; then
		if [ "${VERSION}" = "nightly" ]; then
			cd "${BASE_DIR}"
			curl -sL https://wordpress.org/nightly-builds/wordpress-latest.zip | unzip -q -
			mv "${BASE_DIR}/wordpress" "${BASE_DIR}/wordpress-nightly"
			cd -
		else
			mkdir -p "${BASE_DIR}/wordpress-${VERSION}"
			curl -sL "https://wordpress.org/wordpress-${VERSION}.tar.gz" | tar --strip-components=1 -zxm -f - -C "${BASE_DIR}/wordpress-${VERSION}"
		fi

		curl -sL https://raw.github.com/markoheijnen/wp-mysqli/master/db.php -o "${BASE_DIR}/wordpress-${VERSION}/wp-content/db.php"
	fi

	if [ ! -d "${BASE_DIR}/wordpress-tests-lib-${VERSION}" ]; then
		mkdir -p "${BASE_DIR}/wordpress-tests-lib-${VERSION}"
		svn co --quiet --ignore-externals "https://develop.svn.wordpress.org/${TESTS_TAG}/tests/phpunit/includes/" "${BASE_DIR}/wordpress-tests-lib-${VERSION}/includes"
		svn co --quiet --ignore-externals "https://develop.svn.wordpress.org/${TESTS_TAG}/tests/phpunit/data/"     "${BASE_DIR}/wordpress-tests-lib-${VERSION}/data"
		rm -f "${BASE_DIR}/wordpress-tests-lib-${VERSION}/wp-tests-config-sample.php"
		curl -sL "https://develop.svn.wordpress.org/${TESTS_TAG}/wp-tests-config-sample.php" -o "${BASE_DIR}/wordpress-tests-lib-${VERSION}/wp-tests-config-sample.php"
	fi
}

download_wp "${1:-latest}"
