#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

if [ -x /usr/local/bin/runit-wrapper ] || [ -x /lib/runit/runit-init ] || [ ! -d /var/lib/entrypoint.d ]; then
    exit 0
fi

exec run-parts /var/lib/entrypoint.d
